import type { Metadata } from "next";
import "./globals.css";
import Avisos from "./Components/Avisos";
import Perfil from "./Perfil/page";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
      >
        <Perfil/>
        {children}
    
     

      </body>
    </html>
  );
}
