import type { Metadata } from "next";
import "./globals.css";
import Header from "./Components/Header/Header";
import Footer from "./Components/Footer/Footer";
import BotaoTopo from "./Components/BotaoTopo/Botao";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header/>
        {children}
        <BotaoTopo cor={""} texto={""}/>
        <Footer/>
      </body>
    </html>
  );
}
